name: Deploy Minimarket Backend

on:
  push:
    branches:
      - develop  # Cambia esto si usas una rama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Cambia esto a la versión de Java que uses

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Set up known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 149.50.132.9 >> ~/.ssh/known_hosts || true

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p 5118 root@149.50.132.9 << 'EOF'
            # Entrar al directorio del repositorio
            cd minimarket_virgen_lourdes_backend

            # Hacer pull de los últimos cambios
            git pull origin develop

            # Empaquetar la aplicación
            mvn clean package

            # Copiar el .jar a la ruta deseada
            cp -f target/minimarket-0.0.1-SNAPSHOT.jar /opt/minimarket-backend/  # Ajusta el nombre del archivo si es necesario

            # Reiniciar el servicio
            systemctl restart minimarket-backend.service  # Asegúrate de que este sea el nombre correcto del servicio
          EOF
